In [2]:
# # check numpy version
# import numpy as np
# #1d ,2d, 3d arrays
# # 1d array --> is a single row or column of numbers
# # 2d array --> is a matrix with rows and columns        
# # 3d array --> is a collection of 2d arrays, like a stack of matrices
# # np.__version__
# # check if numpy is compiled with MKL
# print(version := np.__version__)

In [3]:
import numpy as np

lst1=[1,2,3,4,5]
ar1=np.array(lst1)
ar1
print(type(ar1))
print(ar1.shape)

<class 'numpy.ndarray'>
(5,)


In [4]:
#when you have to create an array in a range
ar2=np.arange(1,10)  # start, stop, step
print(ar2)

[1 2 3 4 5 6 7 8 9]


In [5]:
arr6=np.arange(1,31).reshape(5,6)         #reshape is used to convert arr inot another dimension
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [6]:
arr7 = np.random.randint(1,100,10)
arr7

array([95, 14, 97, 49, 36, 72, 45, 98, 20, 74], dtype=int32)

In [7]:
# arr8.ravel()  # converts the array into a 1D array
# arr8.flatten()  # also converts the array into a 1D array, but returns a copy

In [8]:
arr7=np.random.random(10)


In [9]:
arr8=np.arange(60).reshape((12,5))
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [10]:
# arr8=np.arange(60).reshape((12,5))
# print(arr8.shape)
# arr9=arr8
# arr8

In [11]:
##indexing and slicing
## 1d array


In [12]:
# arr8[3:4,2:3]=100
arr8[3:4,2:3]
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [13]:
## 3d array
arr10 = np.arange(225).reshape(3,15,5)
arr10

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [14]:
# arr11=np.random.randint(225)
# arr_11=arr11.reshape(3,15,5)
# arr_11


In [15]:
arr7 = np.random.random((3,15,5))

arr7

array([[[0.66464496, 0.20985777, 0.04361398, 0.6679475 , 0.89538168],
        [0.97750858, 0.19411518, 0.32768682, 0.80509895, 0.95100259],
        [0.61328597, 0.08015232, 0.3035092 , 0.23730821, 0.08056366],
        [0.26337925, 0.80535471, 0.60490167, 0.7920279 , 0.84876742],
        [0.58293019, 0.67255425, 0.85619202, 0.83281468, 0.97899795],
        [0.20113647, 0.85673469, 0.53325801, 0.84861511, 0.66641989],
        [0.2243807 , 0.30191478, 0.79025711, 0.7587424 , 0.40732332],
        [0.59816821, 0.7794288 , 0.0095614 , 0.30492555, 0.36170776],
        [0.88070637, 0.15313008, 0.54320727, 0.92782813, 0.97200536],
        [0.34437659, 0.26385756, 0.9098676 , 0.61392107, 0.12622865],
        [0.7413607 , 0.47601651, 0.16716994, 0.95842282, 0.92047121],
        [0.37344663, 0.9958549 , 0.85747956, 0.84290053, 0.40979481],
        [0.33541515, 0.87354104, 0.97681825, 0.49434714, 0.2344713 ],
        [0.43262089, 0.75094829, 0.7929495 , 0.72344355, 0.89374758],
        [0.41574037,

In [16]:
arr1=np.random.random(50)
arr1=arr1.reshape(1,10,5)
print(arr1)

[[[0.16809755 0.99761289 0.34020693 0.85891034 0.90776277]
  [0.57093889 0.205342   0.37572761 0.98816448 0.81367258]
  [0.14229274 0.16269204 0.05547661 0.08001208 0.44004517]
  [0.91788257 0.31340575 0.3755898  0.05834604 0.7880276 ]
  [0.02287097 0.05961266 0.70151415 0.30401963 0.90788272]
  [0.87416804 0.57810756 0.36938916 0.71233638 0.46111084]
  [0.2900276  0.45589996 0.05128916 0.84797011 0.03014402]
  [0.39128713 0.61627523 0.10903559 0.53917774 0.71040341]
  [0.88735131 0.0208008  0.98330876 0.49779808 0.30449229]
  [0.05254822 0.87358065 0.71904537 0.80121811 0.19114799]]]


In [17]:
arr1=np.random.randint(0,50,size=50)
arr1=arr1.reshape(1,10,5)
print(arr1)

[[[20 41  9 33 25]
  [ 7 11 30  9  5]
  [42 43 26 37  8]
  [47 41 15 35 45]
  [33 30 49 15 24]
  [38 35 35 43 37]
  [38 34  7 23 14]
  [27 11 31 21  7]
  [46 33 13 12  8]
  [29 43 40  5 12]]]
