In [2]:
# # check numpy version
# import numpy as np
# #1d ,2d, 3d arrays
# # 1d array --> is a single row or column of numbers
# # 2d array --> is a matrix with rows and columns        
# # 3d array --> is a collection of 2d arrays, like a stack of matrices
# # np.__version__
# # check if numpy is compiled with MKL
# print(version := np.__version__)

In [2]:
import numpy as np

lst1=[1,2,3,4,5]
ar1=np.array(lst1)
ar1
print(type(ar1))
print(ar1.shape)

<class 'numpy.ndarray'>
(5,)


In [3]:
#when you have to create an array in a range
ar2=np.arange(1,10)  # start, stop, step
print(ar2)

[1 2 3 4 5 6 7 8 9]


In [4]:
arr6=np.arange(1,31).reshape(5,6)         #reshape is used to convert arr inot another dimension
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [5]:
arr7 = np.random.randint(1,100,10)
arr7

array([86,  9, 49, 46, 61,  5, 18, 40, 63, 94], dtype=int32)

In [6]:
# arr8.ravel()  # converts the array into a 1D array
# arr8.flatten()  # also converts the array into a 1D array, but returns a copy

In [7]:
arr7=np.random.random(10)


In [8]:
arr8=np.arange(60).reshape((12,5))
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [9]:
# arr8=np.arange(60).reshape((12,5))
# print(arr8.shape)
# arr9=arr8
# arr8

In [10]:
##indexing and slicing
## 1d array


In [11]:
# arr8[3:4,2:3]=100
arr8[3:4,2:3]
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [14]:
## 3d array
arr10 = np.arange(225).reshape(3,15,5)
arr10

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [19]:
# arr11=np.random.randint(225)
# arr_11=arr11.reshape(3,15,5)
# arr_11


In [25]:
arr7 = np.random.random((3,15,5))

arr7

array([[[0.84090909, 0.19746798, 0.23607782, 0.29010069, 0.14816965],
        [0.28537695, 0.42052488, 0.04200271, 0.58213256, 0.67374838],
        [0.77008148, 0.10954178, 0.77854806, 0.08233413, 0.51821598],
        [0.61660284, 0.64612015, 0.79029342, 0.18346007, 0.1209328 ],
        [0.0087771 , 0.68382126, 0.09132212, 0.8748759 , 0.62985123],
        [0.09138683, 0.90082085, 0.37090586, 0.21942342, 0.77325636],
        [0.55942383, 0.19372779, 0.87511489, 0.1235988 , 0.08098292],
        [0.55730221, 0.42694939, 0.89597397, 0.1607126 , 0.75171833],
        [0.09501006, 0.48499229, 0.23226616, 0.97701204, 0.58006104],
        [0.93504042, 0.80144811, 0.59607673, 0.22142284, 0.23476499],
        [0.22828226, 0.65752317, 0.32184393, 0.20660468, 0.92474032],
        [0.12585007, 0.09340353, 0.29362708, 0.79319212, 0.43082435],
        [0.3542225 , 0.8357205 , 0.63435343, 0.61532319, 0.13737696],
        [0.35480999, 0.77700326, 0.37274687, 0.57848937, 0.69646352],
        [0.14303714,

In [1]:
arr1=np.random.random(50)
arr1=arr1.reshape(1,10,5)
print(arr1)

NameError: name 'np' is not defined

In [40]:
arr1=np.random.randint(0,50,size=50)
arr1=arr1.reshape(1,10,5)
print(arr1)

[[[28 12 48 25  7]
  [28 36 16 11 13]
  [ 7 46 30  0 28]
  [39 40 10 43 25]
  [28 34 21 13  9]
  [40 19 22 45 39]
  [40 46 12  8  8]
  [44 23 48 45 18]
  [35 39 27 18 30]
  [37 29 44 40 38]]]
